import { json } from "express";
import { playerModel } from "../../models/players/player-model";

const databse: playerModel[] = [
  {
    id: 1,
    ovr: 94,
    name: "Ronaldo",
    nationality: "Brasil",
    club: "legends",
    pac: 94,
    sho: 94,
    pas: 79,
    dri: 94,
    def: 43,
    phy: 75,
  },
  {
    id: 2,
    ovr: 93,
    name: "Hamm",
    nationality: "Estados Unidos",
    club: "legends",
    pac: 92,
    sho: 93,
    pas: 86,
    dri: 92,
    def: 54,
    phy: 81,
  },
  {
    id: 3,
    ovr: 91,
    name: "Mbappé",
    nationality: "França",
    club: "Real Madrid",
    pac: 96,
    sho: 91,
    pas: 81,
    dri: 92,
    def: 30,
    phy: 77,
  },
  {
    id: 4,
    ovr: 91,
    name: "Mbappé",
    nationality: "França",
    club: "Real Madrid",
    pac: 96,
    sho: 91,
    pas: 80,
    dri: 92,
    def: 29,
    phy: 76,
  },
  {
    id: 5,
    ovr: 95,
    name: "Pelé",
    nationality: "Brasil",
    club: "legends",
    pac: 93,
    sho: 94,
    pas: 91,
    dri: 94,
    def: 58,
    phy: 74,
  },
  {
    id: 6,
    ovr: 93,
    name: "Beckenbauer",
    nationality: "Alemanha",
    club: "legends",
    pac: 82,
    sho: 73,
    pas: 88,
    dri: 84,
    def: 93,
    phy: 83,
  },
  {
    id: 7,
    ovr: 91,
    name: "Eusébio",
    nationality: "Portugal",
    club: "legends",
    pac: 92,
    sho: 92,
    pas: 84,
    dri: 91,
    def: 44,
    phy: 77,
  },
  {
    id: 8,
    ovr: 90,
    name: "Matthäus",
    nationality: "Alemanha",
    club: "legends",
    pac: 88,
    sho: 87,
    pas: 88,
    dri: 81,
    def: 89,
    phy: 82,
  },
  {
    id: 9,
    ovr: 94,
    name: "Zidane",
    nationality: "França",
    club: "legends",
    pac: 83,
    sho: 90,
    pas: 94,
    dri: 94,
    def: 73,
    phy: 84,
  },
  {
    id: 10,
    ovr: 90,
    name: "Dembélé",
    nationality: "França",
    club: "Paris Saint-Germain",
    pac: 90,
    sho: 89,
    pas: 83,
    dri: 93,
    def: 55,
    phy: 70,
  },
  {
    id: 11,
    ovr: 91,
    name: "Gullit",
    nationality: "Países Baixos",
    club: "legends",
    pac: 86,
    sho: 88,
    pas: 89,
    dri: 87,
    def: 80,
    phy: 88,
  },
  {
    id: 12,
    ovr: 90,
    name: "Formiga",
    nationality: "Brasil",
    club: "legends",
    pac: 82,
    sho: 78,
    pas: 85,
    dri: 85,
    def: 90,
    phy: 86,
  },
  {
    id: 13,
    ovr: 91,
    name: "Henry",
    nationality: "França",
    club: "legends",
    pac: 93,
    sho: 90,
    pas: 84,
    dri: 90,
    def: 51,
    phy: 78,
  },
  {
    id: 14,
    ovr: 92,
    name: "Puskás",
    nationality: "Hungria",
    club: "legends",
    pac: 90,
    sho: 94,
    pas: 89,
    dri: 91,
    def: 45,
    phy: 74,
  },
  {
    id: 15,
    ovr: 91,
    name: "Morgan",
    nationality: "Estados Unidos",
    club: "San Diego Wave",
    pac: 93,
    sho: 90,
    pas: 80,
    dri: 90,
    def: 48,
    phy: 77,
  },
  {
    id: 16,
    ovr: 92,
    name: "Charlton",
    nationality: "Inglaterra",
    club: "legends",
    pac: 90,
    sho: 91,
    pas: 87,
    dri: 91,
    def: 50,
    phy: 74,
  },
  {
    id: 17,
    ovr: 93,
    name: "Cruyff",
    nationality: "Países Baixos",
    club: "legends",
    pac: 90,
    sho: 91,
    pas: 90,
    dri: 94,
    def: 42,
    phy: 73,
  },
  {
    id: 18,
    ovr: 93,
    name: "Maldini",
    nationality: "Itália",
    club: "legends",
    pac: 85,
    sho: 55,
    pas: 75,
    dri: 72,
    def: 95,
    phy: 84,
  },
];

export const findAllPlayers = async (): Promise<playerModel[]> => {
  return databse;
};

export const findPlayerByid = async (
  id: number,
): Promise<playerModel | undefined> => {
  const player = databse.find((player) => player.id === id);
  return player;
};

export const insertPlayer = async (player: playerModel) => {
  databse.push(player);
};

export const deleteOnePlayer = async (id: number) => {
  const index = databse.findIndex((player) => player.id === id);

  if (index !== -1) {
    databse.splice(index, 1);
  }
};
